server {
    listen 80;
    server_name 104.208.69.18.nip.io;

    location /.well-known/acme-challenge/ {
        root /var/www/html/public;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}


server {
    listen 443 ssl;
    server_name 104.208.69.18.nip.io;

    root /var/www/html/public;
    index index.php;

    client_max_body_size 20M;

    ssl_certificate /etc/letsencrypt/live/104.208.69.18.nip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/104.208.69.18.nip.io/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location /.well-known/acme-challenge/ {
	root /var/www/html/public;
        try_files $uri =404;
    }    

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        alias /var/www/html/storage/app/public/;
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        fastcgi_read_timeout 120;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
